name: Build Curriculum
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Prepare build environment
        uses: cachix/install-nix-action@v15
      - name: Connect Shikanime Nix cache
        uses: cachix/cachix-action@v10
        with:
          name: shikanime
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Compile documents
        run: nix build .#curriculum
      - name: Export output path
        run: echo "RELEASE_PATH=$(readlink -f result)" >> $GITHUB_ENV
      - name: Export build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Curriculum
          path: ${{ env.RELEASE_PATH }}
